services:
  ### {{SERVICE}} #########################################################
  {{SERVICE}}:
    hostname: {{SERVICE}}
    image: sparrow-app-{{SERVICE}}:${IMAGE_APP_{{SERVICE_UPPER}}_VERSION} # pull_or_build_app_image(local image=>remote image=>build image)
    container_name: sparrow_container_${CONTAINER_NAMESPACE}_{{SERVICE}}
    platform: ${FROM_PLATFORM}
    restart: always
    environment:
      TZ: ${TZ}
      LANG: C.UTF-8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./{{SERVICE}}/:/home/sparrow/{{SERVICE}}/
      - ./{{SERVICE}}/data/:/var/data/{{SERVICE}}/ # data persistence
    ports:
      # You don't need to expose the port in the Dockerfile.
      - "${{{SERVICE_UPPER}}_HOST_PORT}:${{{SERVICE_UPPER}}_CONTAINER_PORT}"
    networks:
      - backend
    # only for debug
    # command: "tail -f /dev/null"
