services:
  ### NGINX ######################################################
  nginx:
    hostname: nginx
    image: sparrow-app-nginx:${IMAGE_APP_NGINX_VERSION} # pull_or_build_app_image(local image=>remote image=>build image)
    container_name: sparrow_container_${CONTAINER_NAMESPACE}_nginx
    platform: ${FROM_PLATFORM}
    restart: always
    environment:
      TZ: ${TZ}
      LANG: C.UTF-8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/:/home/sparrow/nginx/
      - ./nginx/data/:/var/data/nginx/ # data persistence, use a common data persistence directory /var/data/{SERVICE}
      - ${NGINX_LOG_PATH}:/var/log/nginx/
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available/
    ports:
      # You don't need to expose the port in the Dockerfile.
      - "${NGINX_HOST_HTTP_PORT}:${NGINX_CONTAINER_HTTP_PORT}"
      - "${NGINX_HOST_HTTPS_PORT}:${NGINX_CONTAINER_HTTPS_PORT}"
      - "${NGINX_HOST_GO_PROXY_PORT}:${NGINX_CONTAINER_GO_PROXY_PORT}"
      - "${NGINX_HOST_PHPFPM_PROXY_PORT}:${NGINX_CONTAINER_PHPFPM_PROXY_PORT}"
      - "${NGINX_HOST_PYTHON_PROXY_PORT}:${NGINX_CONTAINER_PYTHON_PROXY_PORT}"
    networks:
      - backend
    # only for debug
    # command: "tail -f /dev/null"
