services:
  ### PYTHON #####################################################
  python:
    hostname: python
    image: sparrow-app-python:${IMAGE_APP_PYTHON_VERSION} # pull_or_build_app_image(local image=>remote image=>build image)
    container_name: sparrow_container_${CONTAINER_NAMESPACE}_python
    platform: ${FROM_PLATFORM}
    restart: always
    environment:
      TZ: ${TZ}
      LANG: C.UTF-8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./python/:/home/sparrow/python/
      - ./python/data/:/var/data/python/ # data persistence
    ports:
      # You don't need to expose the port in the Dockerfile.
      - "${PYTHON_HOST_PORT}:${PYTHON_CONTAINER_PORT}"
    tty: true # must set the field
    # command: "tail -f /dev/null" # only for debug
    networks:
      - backend
    # only for debug
    # command: "tail -f /dev/null"
