services:
  ### PHPFPM #####################################################
  phpfpm:
    hostname: phpfpm
    image: sparrow-app-phpfpm:${IMAGE_APP_PHPFPM_VERSION} # pull_or_build_app_image(local image=>remote image=>build image)
    container_name: sparrow_container_${CONTAINER_NAMESPACE}_phpfpm
    platform: ${FROM_PLATFORM}
    restart: always
    environment:
      TZ: ${TZ}
      LANG: C.UTF-8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./phpfpm/:/home/sparrow/phpfpm/
      - ./phpfpm/data/:/var/data/phpfpm/ # data persistence, use a common data persistence directory /var/data/{SERVICE}
      - ${PHPFPM_LOCALHOST_LARAVEL_APP_LOG_PATH}:${PHPFPM_LARAVEL_APP_LOG_PATH}
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      - "host.docker.internal:${DOCKER_HOST_IP}"
    ports:
      # You don't need to expose the port in the Dockerfile.
      - "${PHPFPM_HOST_PORT}:${PHPFPM_CONTAINER_PORT}"
      - "${PHPFPM_HOST_XDEBUG_PORT}:${PHPFPM_CONTAINER_XDEBUG_PORT}"
    networks:
      - backend
    # only for debug
    # command: "tail -f /dev/null"
