services:
  ### REDIS ######################################################
  redis:
    hostname: redis
    image: sparrow-app-redis:${IMAGE_APP_REDIS_VERSION} # pull_or_build_app_image(local image=>remote image=>build image)
    container_name: sparrow_container_${CONTAINER_NAMESPACE}_redis
    platform: ${FROM_PLATFORM}
    restart: always
    environment:
      TZ: ${TZ}
      LANG: C.UTF-8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./redis/:/home/sparrow/redis/
      - ./redis/data/:/var/data/redis/ # data persistence, use a common data persistence directory /var/data/{SERVICE}
    ports:
      # You don't need to expose the port in the Dockerfile.
      - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"
    networks:
      - backend
    # only for debug
    # command: "tail -f /dev/null"
